version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: N1234n
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: tomas8199
    networks:
      - apinet
    volumes:
     volumes:
      - /home/ec2-user/mydata:/var/lib/mysql
      # - db_data:/var/lib/mysql
  
  myapi:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - apinet
networks:
  apinet:
    driver: bridge

# volumes:
#   db_data: